# nodl_add_test(name
#   EXECUTABLE <exe>
#   NODL_FILE  <file>
#   [PACKAGE   <pkg>]       # defaults to ${PROJECT_NAME}
#   [TIMEOUT   <seconds>]   # defaults to 60
# )
#
# Generates a launch_testing pytest file that starts <exe> from <pkg>, waits for
# the node to appear, introspects its interfaces, and compares them to <file>.
#
# The generated test file is written to
# ${CMAKE_CURRENT_BINARY_DIR}/nodl_tests/<name>.py and registered via
# ament_add_pytest_test so it participates in `colcon test`.
#
# Example:
#   nodl_add_test(my_node_nodl_test
#     EXECUTABLE my_node
#     NODL_FILE  nodl/my_node.nodl.yaml
#   )
#
function(nodl_add_test test_name)
  cmake_parse_arguments(_NAT "" "EXECUTABLE;NODL_FILE;PACKAGE;TIMEOUT" "" ${ARGN})

  if(NOT _NAT_EXECUTABLE)
    message(FATAL_ERROR "nodl_add_test: EXECUTABLE is required")
  endif()
  if(NOT _NAT_NODL_FILE)
    message(FATAL_ERROR "nodl_add_test: NODL_FILE is required")
  endif()
  if(NOT _NAT_PACKAGE)
    set(_NAT_PACKAGE "${PROJECT_NAME}")
  endif()
  if(NOT _NAT_TIMEOUT)
    set(_NAT_TIMEOUT 60)
  endif()

  get_filename_component(_nodl_abs "${_NAT_NODL_FILE}" ABSOLUTE
    BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

  if(NOT EXISTS "${_nodl_abs}")
    message(WARNING
      "nodl_add_test: NoDL file not found at configure time: ${_nodl_abs}")
  endif()

  set(_out_dir "${CMAKE_CURRENT_BINARY_DIR}/nodl_tests")
  file(MAKE_DIRECTORY "${_out_dir}")
  set(_test_file "${_out_dir}/${test_name}.py")

  file(WRITE "${_test_file}"
"# Generated by nodl_add_test — do not edit.
from nodl_test import nodl_conformance_test

generate_test_description, TestNodlConformance = nodl_conformance_test(
    package='${_NAT_PACKAGE}',
    executable='${_NAT_EXECUTABLE}',
    nodl_file='${_nodl_abs}',
    startup_timeout=${_NAT_TIMEOUT},
)
")

  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(${test_name}
    "${_test_file}"
    TIMEOUT ${_NAT_TIMEOUT}
  )
endfunction()
