# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
# generated by datamodel-codegen:
#   filename:  codegen_cpp.schema.yaml

from __future__ import annotations

from typing import Optional

try:
    from pydantic.v1 import BaseModel, Extra, Field, constr
except ImportError:
    from pydantic import BaseModel, Extra, Field, constr


class CodegenBaseClass(BaseModel):
    """
    An included document that provides the generated class's base.

    """

    class Config:
        extra = Extra.forbid

    role: str = Field('BASE_CLASS', const=True)
    class_: constr(regex=r'^[A-Za-z_][A-Za-z0-9_:]*$') = Field(
        ...,
        alias='class',
        description='Fully-qualified C++ class name to inherit from\n(e.g. ``rclcpp::Node``).\n',
    )
    header: str = Field(
        ...,
        description='C++ header to ``#include`` for the base class\n(e.g. ``rclcpp/rclcpp.hpp``).\n',
    )


class CodegenNoGenerate(BaseModel):
    """
    An included document that has an existing implementation
    but does not provide the generated class's base.
    It excludes this document and its transitive includes from generation.

    """

    class Config:
        extra = Extra.forbid

    role: str = Field('NO_GENERATE', const=True)


class CodegenNode(BaseModel):
    """
    The root document being generated.
    Only valid on the root document.

    """

    class Config:
        extra = Extra.forbid

    role: str = Field('NODE', const=True)
    namespace: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*$')] = Field(
        None,
        description='C++ namespace for the generated class and its parameter structs\n(e.g. ``my_pkg::nodes``).\n',
    )
