# Auto-generated by nodl_generator_cpp --cmake-deps
# Do not edit.
set(my_node_base_NODL_SOURCES
  /RESOLVED/input.nodl.yaml
  /RESOLVED/0.nodl.yaml
  /RESOLVED/1.nodl.yaml
)
set(my_node_base_ROS_DEPS
  geometry_msgs
  rclcpp_lifecycle
  std_msgs
)
set(my_node_base_GENERATED_FILES
  my_node_base.hpp
  my_node_base.cpp
)
