# generated by datamodel-codegen:
#   filename:  nodl.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class ScalarType(Enum):
    """
    Scalar types:
    - bool: C++ bool, Python bool
    - int: C++ int64_t, Python int
    - double: C++ double, Python float
    - string: C++ std::string, Python str
    - none: No code generated (used for structure-only nodes)

    """

    bool = "bool"
    int = "int"
    double = "double"
    string = "string"
    none = "none"


class ArrayType(Enum):
    """
    Array types:
    - bool_array: C++ std::vector<bool>, Python [bool]
    - int_array: C++ std::vector<int64_t>, Python [int]
    - double_array: C++ std::vector<double>, Python [float]
    - string_array: C++ std::vector<std::string>, Python [str]

    """

    bool_array = "bool_array"
    int_array = "int_array"
    double_array = "double_array"
    string_array = "string_array"


class CustomValidator(RootModel[list[Any] | float | str | bool | None]):
    root: list[Any] | float | str | bool | None = Field(
        ...,
        description="Custom validator with namespace-qualified function name.\nThe function must:\n- Accept rclcpp::Parameter const& as first argument\n- Accept additional arguments matching the YAML specification\n- Return tl::expected<void, std::string> type\n- Be defined in a header file passed to the code generator\n",
        examples=[None, [1.0, 2.0], ["arg1", "arg2"]],
    )


class History(Enum):
    """
    History policy.
    """

    KEEP_LAST = "KEEP_LAST"
    KEEP_ALL = "KEEP_ALL"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"


class Reliability(Enum):
    """
    Reliability policy.
    """

    RELIABLE = "RELIABLE"
    BEST_EFFORT = "BEST_EFFORT"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"
    BEST_AVAILABLE = "BEST_AVAILABLE"


class Durability(Enum):
    """
    Durability policy.
    """

    TRANSIENT_LOCAL = "TRANSIENT_LOCAL"
    VOLATILE = "VOLATILE"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"
    BEST_AVAILABLE = "BEST_AVAILABLE"


class Liveliness(Enum):
    """
    Liveliness policy.
    """

    AUTOMATIC = "AUTOMATIC"
    MANUAL_BY_TOPIC = "MANUAL_BY_TOPIC"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"
    BEST_AVAILABLE = "BEST_AVAILABLE"


class QosProfile(BaseModel):
    """
    QoS profile settings. Mirrors rcl_interfaces/QoSProfile field
    set and naming, but uses string enums in place of RMW integer
    codes for readability and signed-int nanoseconds in place of
    builtin_interfaces/Duration for ergonomics -- codegen converts
    the int to a Duration. UNKNOWN values from the RMW spec are
    excluded; they are only meaningful for runtime observation.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    history: History = Field(..., description="History policy.")
    depth: conint(ge=1) | None = Field(
        None, description="Queue depth. Required when history is KEEP_LAST."
    )
    reliability: Reliability = Field(..., description="Reliability policy.")
    durability: Durability | None = Field(None, description="Durability policy.")
    deadline_ns: conint(ge=0) | None = Field(
        None,
        description="Deadline between successive messages, in nanoseconds.\nZero means no deadline is enforced. Stored as a signed\n64-bit integer (~292 years range).\n",
    )
    lifespan_ns: conint(ge=0) | None = Field(
        None,
        description="Maximum age of a message before it is dropped, in\nnanoseconds. Zero means messages never expire.\n",
    )
    liveliness: Liveliness | None = Field(None, description="Liveliness policy.")
    liveliness_lease_duration_ns: conint(ge=0) | None = Field(
        None,
        description="Maximum time between liveliness assertions before the\npublisher is considered not alive, in nanoseconds. Zero\nmeans the lease never expires.\n",
    )


class TopicEndpoint(BaseModel):
    """
    Topic endpoint -- same shape for publishers and subscriptions;
    direction is implied by which top-level array contains it.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$") = Field(
        ..., description="Topic name."
    )
    type: constr(
        pattern=r"^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$"
    ) = Field(
        ...,
        description="ROS interface type, format package/(msg|srv|action)?/TypeName.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies msg).\n",
        examples=[
            "std_msgs/msg/String",
            "std_msgs/String",
            "geometry_msgs/msg/Twist",
            "std_srvs/srv/Trigger",
            "lifecycle_msgs/srv/ChangeState",
            "example_interfaces/action/Fibonacci",
            "nav2_msgs/action/NavigateToPose",
        ],
    )
    qos: QosProfile
    description: str | None = None


class ServiceEndpoint(BaseModel):
    """
    Service endpoint -- same shape for servers and clients;
    direction is implied by which top-level array contains it.
    A single qos profile applies; create_service accepts only one
    QoS input and applies it to both the request and response
    sides at runtime.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$") = Field(
        ..., description="Service name."
    )
    type: constr(
        pattern=r"^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$"
    ) = Field(
        ...,
        description="ROS interface type, format package/(msg|srv|action)?/TypeName.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies msg).\n",
        examples=[
            "std_msgs/msg/String",
            "std_msgs/String",
            "geometry_msgs/msg/Twist",
            "std_srvs/srv/Trigger",
            "lifecycle_msgs/srv/ChangeState",
            "example_interfaces/action/Fibonacci",
            "nav2_msgs/action/NavigateToPose",
        ],
    )
    qos: QosProfile | None = None
    description: str | None = None


class ActionEndpoint(BaseModel):
    """
    Action endpoint -- same shape for servers and clients;
    direction is implied by which top-level array contains it.
    The underlying decomposition into goal/result/cancel services
    and feedback/status topics (per rcl_interfaces/Action) is not
    modelled here; it is an implementation concern.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$") = Field(
        ..., description="Action name."
    )
    type: constr(
        pattern=r"^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$"
    ) = Field(
        ...,
        description="ROS interface type, format package/(msg|srv|action)?/TypeName.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies msg).\n",
        examples=[
            "std_msgs/msg/String",
            "std_msgs/String",
            "geometry_msgs/msg/Twist",
            "std_srvs/srv/Trigger",
            "lifecycle_msgs/srv/ChangeState",
            "example_interfaces/action/Fibonacci",
            "nav2_msgs/action/NavigateToPose",
        ],
    )
    description: str | None = None


class Validation(BaseModel):
    """
    Dictionary of validation function names and their arguments.
    Validators can be specified with or without the <> suffix (both are equivalent).
    For example: "bounds<>: [0, 100]" is the same as "bounds: [0, 100]"

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bounds__: list[float] | None = Field(
        None,
        alias="bounds<>",
        description="Inclusive bounds checking: [lower, upper]",
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lt__: list[float] | float | None = Field(
        None,
        alias="lt<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt__: list[float] | float | None = Field(
        None,
        alias="gt<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    lt_eq__: list[float] | float | None = Field(
        None,
        alias="lt_eq<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt_eq__: list[float] | float | None = Field(
        None,
        alias="gt_eq<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    one_of__: list[list[Any]] | None = Field(
        None,
        alias="one_of<>",
        description="Parameter must be one of the specified values: [[val1, val2, ...]]",
        examples=[[["spline", "linear"]], [[0, 1, 2, -1]], [[True, False]]],
    )
    bounds: list[float] | None = Field(
        None,
        description="Inclusive bounds checking: [lower, upper]",
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lt: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    lt_eq: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt_eq: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    one_of: list[list[Any]] | None = Field(
        None,
        description="Parameter must be one of the specified values: [[val1, val2, ...]]",
        examples=[[["spline", "linear"]], [[0, 1, 2, -1]], [[True, False]]],
    )
    not_empty__: list[Any] | None = Field(
        None,
        alias="not_empty<>",
        description="Validator that takes no arguments",
        examples=[None, []],
    )
    not_empty: list[Any] | None = Field(
        None, description="Validator that takes no arguments", examples=[None, []]
    )
    fixed_size__: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None,
        alias="fixed_size<>",
        description="Size/length constraint: [length]",
        examples=[[6], [10], 6],
    )
    size_gt__: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None,
        alias="size_gt<>",
        description="Size/length constraint: [length]",
        examples=[[6], [10], 6],
    )
    size_lt__: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None,
        alias="size_lt<>",
        description="Size/length constraint: [length]",
        examples=[[6], [10], 6],
    )
    fixed_size: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None, description="Size/length constraint: [length]", examples=[[6], [10], 6]
    )
    size_gt: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None, description="Size/length constraint: [length]", examples=[[6], [10], 6]
    )
    size_lt: list[conint(ge=0)] | conint(ge=0) | None = Field(
        None, description="Size/length constraint: [length]", examples=[[6], [10], 6]
    )
    unique__: list[Any] | None = Field(
        None,
        alias="unique<>",
        description="Validator that takes no arguments",
        examples=[None, []],
    )
    subset_of__: list[list[Any]] | None = Field(
        None,
        alias="subset_of<>",
        description="All array elements must be in the specified set: [[val1, val2, ...]]",
        examples=[[["x", "y", "z"]], [[1, 2, 3, 4, 5]]],
    )
    element_bounds__: list[float] | None = Field(
        None,
        alias="element_bounds<>",
        description="Inclusive bounds checking: [lower, upper]",
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lower_element_bounds__: list[float] | float | None = Field(
        None,
        alias="lower_element_bounds<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    upper_element_bounds__: list[float] | float | None = Field(
        None,
        alias="upper_element_bounds<>",
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    unique: list[Any] | None = Field(
        None, description="Validator that takes no arguments", examples=[None, []]
    )
    subset_of: list[list[Any]] | None = Field(
        None,
        description="All array elements must be in the specified set: [[val1, val2, ...]]",
        examples=[[["x", "y", "z"]], [[1, 2, 3, 4, 5]]],
    )
    element_bounds: list[float] | None = Field(
        None,
        description="Inclusive bounds checking: [lower, upper]",
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lower_element_bounds: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    upper_element_bounds: list[float] | float | None = Field(
        None,
        description="Single value comparison: [value] or bare value",
        examples=[[0], [100], [0.001], 15, 0.5],
    )


class ParameterDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: (
        ScalarType
        | ArrayType
        | constr(
            pattern=r"^(string_fixed_[1-9][0-9]*|int_array_fixed_[1-9][0-9]*|double_array_fixed_[1-9][0-9]*|string_array_fixed_[1-9][0-9]*)$"
        )
    ) = Field(..., description="The parameter data type")
    default_value: Any | None = Field(
        None,
        description="Initial value for the parameter. Type must match the declared parameter type.\nIf omitted, the parameter becomes required at initialization.\nSupports: bool, int, double (including NaN, Inf, scientific notation), string,\nand arrays of these types.\n",
    )
    description: str | None = Field(
        "", description="Human-readable description displayed by `ros2 param describe`"
    )
    read_only: bool | None = Field(
        False,
        description="If true, parameter can only be set at launch, not dynamically",
    )
    additional_constraints: str | None = Field(
        "",
        description="Custom constraint metadata (e.g., JSON schema) - not validated by the library",
    )
    validation: Validation | None = None


class NodlDocument(BaseModel):
    """
    NoDL (Node Definition Language) v2 schema.

    Describes the public ROS interface of a single ROS 2 node:
    parameters, publishers, subscriptions, service servers/clients,
    and action servers/clients. Field names align with rcl_interfaces
    and rosgraph_msgs (Topic, Service, Action) so a NoDL document
    maps cleanly onto runtime introspection types.

    Node identity (name, package, namespace) is established by the
    enclosing package and the file's location within it, not declared
    inside the document.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    nodl_version: Literal[2] = Field(
        ..., description="NoDL schema major version this document targets."
    )
    description: str | None = Field(
        None, description="Human-readable description of what this node does."
    )
    parameters: dict[str, ParameterDefinition] | None = Field(
        None,
        description="ROS parameters declared by this node, keyed by parameter name.\nParameter shape is borrowed from generate_parameter_library\n(see parameter.schema.yaml).\n",
    )
    publishers: list[TopicEndpoint] | None = Field(
        None, description="Topic publishers exposed by this node."
    )
    subscriptions: list[TopicEndpoint] | None = Field(
        None, description="Topic subscriptions consumed by this node."
    )
    service_servers: list[ServiceEndpoint] | None = Field(
        None, description="Service servers exposed by this node."
    )
    service_clients: list[ServiceEndpoint] | None = Field(
        None, description="Service clients used by this node."
    )
    action_servers: list[ActionEndpoint] | None = Field(
        None, description="Action servers exposed by this node."
    )
    action_clients: list[ActionEndpoint] | None = Field(
        None, description="Action clients used by this node."
    )
