# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
# generated by datamodel-codegen:
#   filename:  codegen_python.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

try:
    from pydantic.v1 import BaseModel, Extra, Field, constr
except ImportError:
    from pydantic import BaseModel, Extra, Field, constr


class Role(Enum):
    """
    How this document's implementation participates in code generation.
    ``BASE_CLASS`` selects the generated class's base, while ``NO_GENERATE``
    excludes this document and its transitive includes from generation.

    """

    BASE_CLASS = 'BASE_CLASS'
    NO_GENERATE = 'NO_GENERATE'


class CodegenPython(BaseModel):
    """
    Metadata validated and consumed by nodl_generator_py.
    """

    class Config:
        extra = Extra.forbid

    role: Role = Field(
        ...,
        description="How this document's implementation participates in code generation.\n``BASE_CLASS`` selects the generated class's base, while ``NO_GENERATE``\nexcludes this document and its transitive includes from generation.\n",
    )
    module: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$')] = None
    class_: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*$')] = Field(None, alias='class')
    publisher_method: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*$')] = 'create_publisher'
