# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
# generated by datamodel-codegen:
#   filename:  codegen_python.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

try:
    from pydantic.v1 import BaseModel, Extra, Field, constr
except ImportError:
    from pydantic import BaseModel, Extra, Field, constr


class Role(Enum):
    BASE_CLASS = 'BASE_CLASS'


class CodegenPython(BaseModel):
    """
    Metadata validated and consumed by nodl_generator_py.
    """

    class Config:
        extra = Extra.forbid

    role: Role
    module: constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$')
    class_: constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*$') = Field(..., alias='class')
    publisher_method: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_]*$')] = 'create_publisher'
