#pragma once

#include <string>

#include "lifecycle_pubsub_node.hpp"  // generated by nodl_generate_cpp(... LIFECYCLE)

class LifecyclePubsubNode : public LifecyclePubsubNodeBase
{
public:
  using LifecyclePubsubNodeBase::LifecyclePubsubNodeBase;

  std::string last_received;
  int receive_count{0};

protected:
  void on_lc_echo_in(std_msgs::msg::String::ConstSharedPtr msg) override;
};
