#pragma once

#include "params_node.hpp"  // generated by nodl_generate_cpp(params_node ...)

// Re-export `params_` to public so the test can read it directly.
class ParamsNode : public ParamsNodeBase
{
public:
  using ParamsNodeBase::ParamsNodeBase;
  using ParamsNodeBase::params_;
};
