#pragma once

#include <string>

#include "pubsub_node.hpp"  // generated by nodl_generate_cpp(pubsub_node ...)

class PubsubNode : public PubsubNodeBase
{
public:
  using PubsubNodeBase::PubsubNodeBase;

  std::string last_received;
  int receive_count{0};

protected:
  void on_echo_in(std_msgs::msg::String::ConstSharedPtr msg) override;
};
