#pragma once

#include "service_node.hpp"  // generated by nodl_generate_cpp(service_node ...)

class ServiceNode : public ServiceNodeBase
{
public:
  using ServiceNodeBase::ServiceNodeBase;

  int add_call_count{0};

  // Expose the generated client for the test to drive a delegate call.
  rclcpp::Client<example_interfaces::srv::AddTwoInts>::SharedPtr delegate_client()
  {
    return cli_delegate_add_;
  }

protected:
  void on_add(
    example_interfaces::srv::AddTwoInts::Request::SharedPtr request,
    example_interfaces::srv::AddTwoInts::Response::SharedPtr response) override;
};
