name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.1

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: humble
            image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
          - distro: jazzy
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
          - distro: kilted
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
          - distro: lyrical
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-lyrical-ros-base-latest
          - distro: rolling
            image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: nodl nodl_schema ros2nodl
          target-ros2-distro: ${{ matrix.distro }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: colcon-logs-${{ matrix.distro }}
          path: ros_ws/log
